services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    
  api:
    container_name: rest-api-crud
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    environment:
      - NODE_ENV=production
    env_file: 
      - .env
      - .env.production
    depends_on:
      - postgres
      - redis

