services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # restart: always
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    
  api:
    build: .
    restart: unless-stopped
    container_name: rest-api-crud
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - .:/api
