services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # restart: always
    restart: unless-stopped
    env_file: .env.development
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest-api-crud

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    
  api:
    build: .
    restart: unless-stopped
    container_name: rest-api-crud
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    env_file: 
      - .env
      - .env.development
