export const publisherSeed = [
  {
    publisher_id: 1,
    publisher_name: "Lueilwitz LLC",
    contact_name: null,
    phone_number: "269-515-3090",
  },
  {
    publisher_id: 2,
    publisher_name: "Roberts LLC",
    contact_name: "Di Fransman",
    phone_number: "227-346-9985",
  },
  {
    publisher_id: 3,
    publisher_name: "Cruickshank-Cartwright",
    contact_name: null,
    phone_number: "956-835-5812",
  },
  {
    publisher_id: 4,
    publisher_name: "West and Sons",
    contact_name: "Maris Weatherall",
    phone_number: "985-886-1764",
  },
  {
    publisher_id: 5,
    publisher_name: "Leffler-Hoppe",
    contact_name: "Atlanta Deedes",
    phone_number: "145-349-7262",
  },
  {
    publisher_id: 6,
    publisher_name: "Schiller-Goodwin",
    contact_name: "Rachael McGaraghan",
    phone_number: "920-309-1292",
  },
  {
    publisher_id: 7,
    publisher_name: "Wolf, Parisian and Rempel",
    contact_name: "Karmen Hannah",
    phone_number: "480-220-9050",
  },
  {
    publisher_id: 8,
    publisher_name: "Padberg and Sons",
    contact_name: "Gertrudis Huckerby",
    phone_number: "786-464-5517",
  },
  {
    publisher_id: 9,
    publisher_name: "Bruen-Zieme",
    contact_name: "Enrico Wyness",
    phone_number: "963-810-3973",
  },
  {
    publisher_id: 10,
    publisher_name: "Will, Predovic and Rau",
    contact_name: null,
    phone_number: "274-118-6155",
  },
  {
    publisher_id: 11,
    publisher_name: "Schuppe, Morissette and Turcotte",
    contact_name: "Tucky Jubb",
    phone_number: "195-206-0314",
  },
  {
    publisher_id: 12,
    publisher_name: "Reynolds, Stoltenberg and Herzog",
    contact_name: null,
    phone_number: "282-975-8933",
  },
  {
    publisher_id: 13,
    publisher_name: "Schamberger Inc",
    contact_name: null,
    phone_number: "269-452-1309",
  },
  {
    publisher_id: 14,
    publisher_name: "Bartell-Walter",
    contact_name: null,
    phone_number: "848-168-5168",
  },
  {
    publisher_id: 15,
    publisher_name: "Adams-Turcotte",
    contact_name: "Pepi Dagnan",
    phone_number: "248-974-8633",
  },
  {
    publisher_id: 16,
    publisher_name: "Mosciski-Legros",
    contact_name: "Aidan Upsale",
    phone_number: "680-640-4397",
  },
  {
    publisher_id: 17,
    publisher_name: "Hoppe, Nienow and Muller",
    contact_name: null,
    phone_number: "245-160-6759",
  },
  {
    publisher_id: 18,
    publisher_name: "Emard-Paucek",
    contact_name: "Petunia Ortzen",
    phone_number: "401-166-4524",
  },
  {
    publisher_id: 19,
    publisher_name: "Renner-Leffler",
    contact_name: "Donica Jirousek",
    phone_number: "643-476-8559",
  },
  {
    publisher_id: 20,
    publisher_name: "McKenzie LLC",
    contact_name: "Terri Mulmuray",
    phone_number: "952-257-7835",
  },
  {
    publisher_id: 21,
    publisher_name: "Bechtelar, Dietrich and Stracke",
    contact_name: "Fredra Barley",
    phone_number: "423-965-2955",
  },
  {
    publisher_id: 22,
    publisher_name: "Fadel, Zieme and Adams",
    contact_name: "Bird Habbon",
    phone_number: "201-780-9121",
  },
  {
    publisher_id: 23,
    publisher_name: "Green, Schoen and Fisher",
    contact_name: null,
    phone_number: "104-489-3448",
  },
  {
    publisher_id: 24,
    publisher_name: "Mann-Corkery",
    contact_name: "Ruttger Legges",
    phone_number: "357-345-1735",
  },
  {
    publisher_id: 25,
    publisher_name: "Muller-Effertz",
    contact_name: "Quinton Bendixen",
    phone_number: "345-708-2268",
  },
  {
    publisher_id: 26,
    publisher_name: "Kuhlman LLC",
    contact_name: null,
    phone_number: "590-270-3160",
  },
  {
    publisher_id: 27,
    publisher_name: "Cartwright, Walter and Lesch",
    contact_name: "Ludwig McKim",
    phone_number: "532-995-1783",
  },
  {
    publisher_id: 28,
    publisher_name: "O'Keefe, Cummerata and Kshlerin",
    contact_name: "Konstance Lippard",
    phone_number: "221-939-1006",
  },
  {
    publisher_id: 29,
    publisher_name: "West-Schaefer",
    contact_name: null,
    phone_number: "847-274-4564",
  },
  {
    publisher_id: 30,
    publisher_name: "Wiza-Parisian",
    contact_name: "Devin Weddeburn",
    phone_number: "147-928-9210",
  },
  {
    publisher_id: 31,
    publisher_name: "Dare, Gutkowski and Schuppe",
    contact_name: null,
    phone_number: "991-409-8859",
  },
  {
    publisher_id: 32,
    publisher_name: "Hagenes LLC",
    contact_name: "Belle Tuppeny",
    phone_number: "176-172-1645",
  },
  {
    publisher_id: 33,
    publisher_name: "Cummerata-Reichert",
    contact_name: "Hunt Konig",
    phone_number: "112-316-0778",
  },
  {
    publisher_id: 34,
    publisher_name: "Brakus, Stroman and Reichert",
    contact_name: "Dore Forre",
    phone_number: "196-589-3982",
  },
  {
    publisher_id: 35,
    publisher_name: "Schamberger and Sons",
    contact_name: "Gussie McKeating",
    phone_number: "492-829-5070",
  },
  {
    publisher_id: 36,
    publisher_name: "Lynch Group",
    contact_name: "Brenden Tumpane",
    phone_number: "162-789-3549",
  },
  {
    publisher_id: 37,
    publisher_name: "Swift-Kiehn",
    contact_name: null,
    phone_number: "627-154-7617",
  },
  {
    publisher_id: 38,
    publisher_name: "Homenick Inc",
    contact_name: null,
    phone_number: "567-769-0348",
  },
  {
    publisher_id: 39,
    publisher_name: "Reinger-Legros",
    contact_name: null,
    phone_number: "424-701-6576",
  },
  {
    publisher_id: 40,
    publisher_name: "Lindgren, Goodwin and Lebsack",
    contact_name: "Jacklyn Edlington",
    phone_number: "626-591-3935",
  },
  {
    publisher_id: 41,
    publisher_name: "Hyatt Group",
    contact_name: null,
    phone_number: "642-695-3362",
  },
  {
    publisher_id: 42,
    publisher_name: "Treutel-Lubowitz",
    contact_name: null,
    phone_number: "288-344-3408",
  },
  {
    publisher_id: 43,
    publisher_name: "Klein, Kihn and Wintheiser",
    contact_name: "Thaddus Pepi",
    phone_number: "710-967-8106",
  },
  {
    publisher_id: 44,
    publisher_name: "Powlowski Group",
    contact_name: null,
    phone_number: "224-572-5428",
  },
  {
    publisher_id: 45,
    publisher_name: "Walter-Heller",
    contact_name: "Kit Gooder",
    phone_number: "793-930-5313",
  },
  {
    publisher_id: 46,
    publisher_name: "Yundt, Larson and Wintheiser",
    contact_name: null,
    phone_number: "689-611-6009",
  },
  {
    publisher_id: 47,
    publisher_name: "Beatty-Tremblay",
    contact_name: "Aubert Falk",
    phone_number: "999-924-9353",
  },
  {
    publisher_id: 48,
    publisher_name: "Haley-Schoen",
    contact_name: null,
    phone_number: "445-509-8339",
  },
  {
    publisher_id: 49,
    publisher_name: "Ankunding-Ullrich",
    contact_name: "Edin Gettens",
    phone_number: "737-306-2623",
  },
  {
    publisher_id: 50,
    publisher_name: "Haag-Hammes",
    contact_name: null,
    phone_number: "574-783-2427",
  },
  {
    publisher_id: 51,
    publisher_name: "Kuvalis, Koepp and Ward",
    contact_name: null,
    phone_number: "977-755-5345",
  },
  {
    publisher_id: 52,
    publisher_name: "Gibson, Rice and Dach",
    contact_name: "Farrand Surplice",
    phone_number: "141-205-7958",
  },
  {
    publisher_id: 53,
    publisher_name: "Haag Group",
    contact_name: "Welby Waltho",
    phone_number: "352-287-8634",
  },
  {
    publisher_id: 54,
    publisher_name: "Kertzmann, Abbott and Schiller",
    contact_name: "Kaycee Bachshell",
    phone_number: "418-279-8103",
  },
  {
    publisher_id: 55,
    publisher_name: "Schoen-Ankunding",
    contact_name: "Jenine Scholig",
    phone_number: "550-207-9251",
  },
  {
    publisher_id: 56,
    publisher_name: "Klocko, Ruecker and Goodwin",
    contact_name: "Gianina Folkard",
    phone_number: "945-422-6392",
  },
  {
    publisher_id: 57,
    publisher_name: "Altenwerth-Reichel",
    contact_name: "Judah De Santos",
    phone_number: "497-349-9293",
  },
  {
    publisher_id: 58,
    publisher_name: "Yost-Moore",
    contact_name: null,
    phone_number: "429-686-4839",
  },
  {
    publisher_id: 59,
    publisher_name: "Braun-Beatty",
    contact_name: null,
    phone_number: "859-278-4363",
  },
  {
    publisher_id: 60,
    publisher_name: "Emmerich LLC",
    contact_name: "Annabell Kaindl",
    phone_number: "626-921-4150",
  },
  {
    publisher_id: 61,
    publisher_name: "Keeling-Kirlin",
    contact_name: "Jedd Harrigan",
    phone_number: "396-776-5303",
  },
  {
    publisher_id: 62,
    publisher_name: "Upton LLC",
    contact_name: "Oswell Willimot",
    phone_number: "797-195-2464",
  },
  {
    publisher_id: 63,
    publisher_name: "Cormier Inc",
    contact_name: null,
    phone_number: "369-691-0259",
  },
  {
    publisher_id: 64,
    publisher_name: "Reichel-Gulgowski",
    contact_name: null,
    phone_number: "239-686-9596",
  },
  {
    publisher_id: 65,
    publisher_name: "Ward-Klocko",
    contact_name: null,
    phone_number: "107-406-1336",
  },
  {
    publisher_id: 66,
    publisher_name: "Botsford-Lesch",
    contact_name: null,
    phone_number: "213-656-7543",
  },
  {
    publisher_id: 67,
    publisher_name: "Johns-Block",
    contact_name: null,
    phone_number: "770-954-9564",
  },
  {
    publisher_id: 68,
    publisher_name: "Rice, Quitzon and Beatty",
    contact_name: "Daryle Wooffitt",
    phone_number: "397-381-8986",
  },
  {
    publisher_id: 69,
    publisher_name: "Walter and Sons",
    contact_name: "Dana McKendry",
    phone_number: "678-601-5888",
  },
  {
    publisher_id: 70,
    publisher_name: "Runolfsson and Sons",
    contact_name: "Ashlen Eley",
    phone_number: "272-359-3706",
  },
  {
    publisher_id: 71,
    publisher_name: "Sipes LLC",
    contact_name: "Tildi Skillitt",
    phone_number: "720-150-9138",
  },
  {
    publisher_id: 72,
    publisher_name: "Borer-MacGyver",
    contact_name: null,
    phone_number: "529-910-2129",
  },
  {
    publisher_id: 73,
    publisher_name: "Lueilwitz-Conroy",
    contact_name: "Burch Whitcomb",
    phone_number: "414-212-1677",
  },
  {
    publisher_id: 74,
    publisher_name: "Armstrong and Sons",
    contact_name: "Lowrance Keems",
    phone_number: "576-509-3873",
  },
  {
    publisher_id: 75,
    publisher_name: "Predovic, Smith and Rogahn",
    contact_name: null,
    phone_number: "213-660-5811",
  },
  {
    publisher_id: 76,
    publisher_name: "Johnston, Dare and Swaniawski",
    contact_name: "Sully Pile",
    phone_number: "616-403-8270",
  },
  {
    publisher_id: 77,
    publisher_name: "Adams Inc",
    contact_name: "Clare Lambourn",
    phone_number: "662-519-5154",
  },
  {
    publisher_id: 78,
    publisher_name: "Senger Inc",
    contact_name: null,
    phone_number: "290-734-6394",
  },
  {
    publisher_id: 79,
    publisher_name: "Jacobi, Thompson and Rice",
    contact_name: "Nike Hardin",
    phone_number: "747-112-3082",
  },
  {
    publisher_id: 80,
    publisher_name: "Johnston Inc",
    contact_name: "Keane McGinlay",
    phone_number: "784-585-9563",
  },
  {
    publisher_id: 81,
    publisher_name: "Abshire-Farrell",
    contact_name: "Tildie Dorking",
    phone_number: "910-966-6762",
  },
  {
    publisher_id: 82,
    publisher_name: "Davis-Berge",
    contact_name: "Cassie Steffan",
    phone_number: "402-279-5569",
  },
  {
    publisher_id: 83,
    publisher_name: "Moen and Sons",
    contact_name: null,
    phone_number: "253-155-3549",
  },
  {
    publisher_id: 84,
    publisher_name: "Hegmann and Sons",
    contact_name: "Marilee Domerque",
    phone_number: "116-842-9548",
  },
  {
    publisher_id: 85,
    publisher_name: "Glover, Dooley and Jast",
    contact_name: "Tori Shelliday",
    phone_number: "819-342-9852",
  },
  {
    publisher_id: 86,
    publisher_name: "Walter-Friesen",
    contact_name: null,
    phone_number: "162-505-7889",
  },
  {
    publisher_id: 87,
    publisher_name: "O'Connell Inc",
    contact_name: "Alexia Bellie",
    phone_number: "884-940-3919",
  },
  {
    publisher_id: 88,
    publisher_name: "Schimmel and Sons",
    contact_name: "Lenka Bulmer",
    phone_number: "252-365-8329",
  },
  {
    publisher_id: 89,
    publisher_name: "Schmeler-Hoppe",
    contact_name: "Aurea Zolini",
    phone_number: "895-492-4800",
  },
  {
    publisher_id: 90,
    publisher_name: "Kuphal LLC",
    contact_name: "Roshelle Yearns",
    phone_number: "862-729-9745",
  },
  {
    publisher_id: 91,
    publisher_name: "O'Connell, Green and Treutel",
    contact_name: "Jean Lamps",
    phone_number: "988-464-7946",
  },
  {
    publisher_id: 92,
    publisher_name: "Runte-Wisoky",
    contact_name: "Broderic Lernihan",
    phone_number: "584-173-2487",
  },
  {
    publisher_id: 93,
    publisher_name: "Bruen-Medhurst",
    contact_name: null,
    phone_number: "944-481-6486",
  },
  {
    publisher_id: 94,
    publisher_name: "Marquardt, Kulas and Maggio",
    contact_name: "Alec Obeney",
    phone_number: "697-651-3036",
  },
  {
    publisher_id: 95,
    publisher_name: "Schamberger, Harris and Halvorson",
    contact_name: "Delaney Whitehall",
    phone_number: "931-892-1991",
  },
  {
    publisher_id: 96,
    publisher_name: "Johns Inc",
    contact_name: "Guntar Scripture",
    phone_number: "155-738-6004",
  },
  {
    publisher_id: 97,
    publisher_name: "Cummings, Rath and Stanton",
    contact_name: "Madalena Sloan",
    phone_number: "373-592-2001",
  },
  {
    publisher_id: 98,
    publisher_name: "Casper, Fahey and Schaden",
    contact_name: "Bo Stutt",
    phone_number: "469-884-8230",
  },
  {
    publisher_id: 99,
    publisher_name: "Rath LLC",
    contact_name: null,
    phone_number: "687-992-5304",
  },
  {
    publisher_id: 100,
    publisher_name: "Fisher Inc",
    contact_name: "Lutero Gribble",
    phone_number: "591-542-1701",
  },
  {
    publisher_id: 101,
    publisher_name: "Wehner-Kub",
    contact_name: "Arly Petrusch",
    phone_number: "219-348-8816",
  },
  {
    publisher_id: 102,
    publisher_name: "Keeling, Gibson and Hudson",
    contact_name: "Shirleen Benitti",
    phone_number: "162-242-8474",
  },
  {
    publisher_id: 103,
    publisher_name: "Reinger-Hodkiewicz",
    contact_name: "Teddy Lockery",
    phone_number: "315-947-3596",
  },
  {
    publisher_id: 104,
    publisher_name: "Emmerich-Rogahn",
    contact_name: "Grazia Scotchmor",
    phone_number: "771-841-3435",
  },
  {
    publisher_id: 105,
    publisher_name: "Bins and Sons",
    contact_name: "Fletcher McOmish",
    phone_number: "493-991-5862",
  },
  {
    publisher_id: 106,
    publisher_name: "Leuschke LLC",
    contact_name: "Danni Atger",
    phone_number: "132-962-5629",
  },
  {
    publisher_id: 107,
    publisher_name: "Heathcote-Erdman",
    contact_name: "Vasily Ropking",
    phone_number: "162-311-9235",
  },
  {
    publisher_id: 108,
    publisher_name: "Runte and Sons",
    contact_name: null,
    phone_number: "899-491-9628",
  },
  {
    publisher_id: 109,
    publisher_name: "O'Conner and Sons",
    contact_name: "Annadiana Auckland",
    phone_number: "851-338-0299",
  },
  {
    publisher_id: 110,
    publisher_name: "Lehner-Powlowski",
    contact_name: "Bendite Tarpey",
    phone_number: "752-668-5870",
  },
  {
    publisher_id: 111,
    publisher_name: "Bahringer-Fisher",
    contact_name: null,
    phone_number: "829-736-0335",
  },
  {
    publisher_id: 112,
    publisher_name: "Daniel LLC",
    contact_name: "Edyth Megarry",
    phone_number: "913-277-5216",
  },
  {
    publisher_id: 113,
    publisher_name: "Bins LLC",
    contact_name: "Morlee Trinke",
    phone_number: "370-842-2205",
  },
  {
    publisher_id: 114,
    publisher_name: "Sauer, Lowe and Bartoletti",
    contact_name: "Allyn Romke",
    phone_number: "712-910-2064",
  },
  {
    publisher_id: 115,
    publisher_name: "Friesen Inc",
    contact_name: "Raul Opie",
    phone_number: "639-782-1084",
  },
  {
    publisher_id: 116,
    publisher_name: "Will Group",
    contact_name: "Clevie Meegan",
    phone_number: "848-740-6600",
  },
  {
    publisher_id: 117,
    publisher_name: "Tillman-Tremblay",
    contact_name: "Orton Lethley",
    phone_number: "996-991-0188",
  },
  {
    publisher_id: 118,
    publisher_name: "Barton, Ritchie and Walker",
    contact_name: "Chet Luchetti",
    phone_number: "727-303-6565",
  },
  {
    publisher_id: 119,
    publisher_name: "Leffler Group",
    contact_name: "Yul Gravey",
    phone_number: "230-155-9194",
  },
  {
    publisher_id: 120,
    publisher_name: "McGlynn, Schamberger and Bednar",
    contact_name: "Harrison O'Dougherty",
    phone_number: "722-209-8409",
  },
  {
    publisher_id: 121,
    publisher_name: "Hilll-Fritsch",
    contact_name: null,
    phone_number: "350-534-3452",
  },
  {
    publisher_id: 122,
    publisher_name: "Braun, Heaney and Pacocha",
    contact_name: "Luise Brookes",
    phone_number: "431-406-2213",
  },
  {
    publisher_id: 123,
    publisher_name: "Funk Group",
    contact_name: "Staffard Ingarfill",
    phone_number: "162-958-7232",
  },
  {
    publisher_id: 124,
    publisher_name: "Orn and Sons",
    contact_name: "Devlin Girvan",
    phone_number: "805-878-0669",
  },
  {
    publisher_id: 125,
    publisher_name: "Hackett Inc",
    contact_name: "Almire Chatelet",
    phone_number: "919-672-5886",
  },
  {
    publisher_id: 126,
    publisher_name: "Green, Pollich and Weber",
    contact_name: "Arleyne Dancer",
    phone_number: "240-716-6380",
  },
  {
    publisher_id: 127,
    publisher_name: "Reinger, Kihn and Hettinger",
    contact_name: "Briggs Yakov",
    phone_number: "221-835-9263",
  },
  {
    publisher_id: 128,
    publisher_name: "West Group",
    contact_name: "Clarey Ledington",
    phone_number: "625-460-3938",
  },
  {
    publisher_id: 129,
    publisher_name: "Brown, Champlin and Predovic",
    contact_name: "Doro Lung",
    phone_number: "789-716-7129",
  },
  {
    publisher_id: 130,
    publisher_name: "Hagenes, Wilderman and Auer",
    contact_name: "Sunshine Westley",
    phone_number: "820-404-4004",
  },
  {
    publisher_id: 131,
    publisher_name: "O'Reilly, Bosco and Greenfelder",
    contact_name: null,
    phone_number: "922-261-8757",
  },
  {
    publisher_id: 132,
    publisher_name: "Thiel Group",
    contact_name: "Sacha Lapham",
    phone_number: "168-119-4866",
  },
]
